# Generated by Django 3.1.1 on 2020-10-20 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.fields import ArrayField
import jsonfield


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_streaming', models.BooleanField(default=False)),
                ('x_data_date', jsonfield.JSONField()),
                ('y_data', jsonfield.JSONField()),
                ('countries', jsonfield.JSONField()),
                ('resource', models.IntegerField(default=0)),
                ('user',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keywords',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_secret', models.CharField(max_length=100)),
                ('used_count', models.IntegerField(default=0)),
                ('token_check', models.BooleanField()),
                ('user',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('original_tweet_id', models.TextField()),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('country', models.TextField()),
                ('label', models.TextField()),
                ('score', models.DecimalField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets',
                                              to='event_detection.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_subject', models.TextField()),
                ('k_predicate', models.TextField()),
                ('k_object', models.TextField()),
                ('subject_type', models.CharField(default='', max_length=100)),
                ('object_type', models.CharField(default='', max_length=100)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge',
                                            to='event_detection.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TopicsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_topic', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets',
                                              to='event_detection.keyword')),

            ],
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.TextField()),
                ('notrend', models.IntegerField()),
                ('x_data_date_event', jsonfield.JSONField()),
                ('y_data_event', jsonfield.JSONField()),
                ('y_proportion', jsonfield.JSONField()),
                ('y_pos_sentiment', jsonfield.JSONField()),
                ('y_neg_sentiment', jsonfield.JSONField()),
                ('y_neu_sentiment', jsonfield.JSONField()),
                ('country', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets',
                                              to='event_detection.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend', models.TextField()),
                ('begin_time', models.TextField()),
                ('end_time', models.TextField()),
                ('country', models.TextField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets',
                                              to='event_detection.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Temporal_knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_subject', models.TextField()),
                ('k_predicate', models.TextField()),
                ('k_object', models.TextField()),
                ('temporal_start', models.TextField()),
                ('temporal_end', models.TextField()),
                ('mentions', models.IntegerField()),
                ('occurrence', ArrayField(ArrayField(models.IntegerField()))),
                ('diffuse_degree', ArrayField(ArrayField(models.IntegerField()))),
                ('diffuse_sensitivity', ArrayField(ArrayField(models.IntegerField()))),
                ('group_tweets_id', ArrayField(ArrayField(models.IntegerField()))),
                ('is_new_knowledge', models.CharField(default='', max_length=100)),
                ('timeline', jsonfield.JSONField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets',
                                              to='event_detection.keyword')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge',
                                            to='event_detection.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255)),

            ],
        ),
    ]
